/* Moneyland Corporation — Gurgaon Verified Property Portal */
const ML={
 name:'Moneyland Corporation', tagline:'Gurgaon Ki 1 Property · 1 Owner · 1 Public List',
 phone:'8178593108', whatsapp:'918178593108', email:'rrahmawat@gmail.com',
 gst:'06CKJPR5013B1ZH', rera:'RC/HARERA/GGM/4078/3673/2026/113',
 address:'R1/205, M3M 65th Avenue, Sector 65, Gurgaon, Gurugram, Haryana - 122018',
 bidRent:5000,bidBuy:50000,lifeSubscription:100000
};
const WHATS=`https://wa.me/${ML.whatsapp}`;
const categories=[['Residential Flat','flat'],['Luxury Floor / Builder Floor','floor'],['Villa','villa'],['Plot / Residential Land','plot'],['Retail Shop','retail'],['Showroom','showroom'],['Food Court','foodcourt'],['Office Space','office'],['Industrial Land','industrial'],['Agricultural Land','agricultural'],['Farmhouse','farmhouse'],['Warehouse','warehouse'],['PG / Rental','rental'],['Commercial Property','commercial'],['Other','other']];
const sectors=Array.from({length:115},(_,i)=>`Sector ${i+1}`);
const localities=[
  // Gurgaon sectors — location only; projects are intentionally excluded from this list.
  ...Array.from({length:115},(_,i)=>`Sector ${i+1}`),
  // Major roads / corridors
  'Golf Course Road','Golf Course Extension Road','MG Road','Sohna Road','Dwarka Expressway','NH-48 / Delhi-Jaipur Highway','SPR / Southern Peripheral Road','Northern Peripheral Road','Pataudi Road','Basai Road','Farrukhnagar Road','Sohna Elevated Road','Faridabad-Gurgaon Road','KMP Expressway','Manesar Road','Old Delhi Road','Mehrauli-Gurgaon Road','Palam Vihar Road','Sheetla Mata Road','Railway Road','New Railway Road','Huda City Centre Road','Golf Course Road Extension','Sector Road 55/56','Sector Road 57/58','Sector Road 60/61','Sector Road 65/66','Sector Road 67/68','Sector Road 70/70A','Sector Road 75/76','Sector Road 79/80','Sector Road 82/83','Sector Road 84/85','Sector Road 88/89','Sector Road 90/91','Sector Road 92/93','Sector Road 102/103','Sector Road 104/105','Sector Road 106/107','Sector Road 109/110','Sector Road 111/112','Sector Road 113/114','Sector Road 115/116',
  // Established colonies / residential localities
  'DLF Phase 1','DLF Phase 2','DLF Phase 3','DLF Phase 4','DLF Phase 5','Sushant Lok 1','Sushant Lok 2','Sushant Lok 3','South City 1','South City 2','Nirvana Country','Palam Vihar','New Palam Vihar','Udyog Vihar','Dundahera','Sikanderpur','Chakkarpur','Wazirabad','Kanhai','Arjun Nagar','Shivaji Nagar','Jyoti Park','Rajendra Park','Laxman Vihar','Ashok Vihar','Madanpuri','Pace City 1','Pace City 2','Maruti Udyog','Housing Board Colony','Patel Nagar','Jacobpura','Krishna Nagar','Saraswati Vihar','Basai','Khandsa','Rajiv Nagar','Subhash Nagar','Model Town','Civil Lines','Sector 15 Part 1','Sector 15 Part 2','Sector 17','Sector 18','Sector 21','Sector 22','Sector 23','Sector 23A','Carterpuri','Daultabad','Dhankot','Garhi Harsaru','Harsaru','Kadipur','Gurgaon Village','Nathupur','Choma','Sadhhrana','Behrampur','Ghatta','Gwal Pahari','Ghata','Bhondsi','Badshahpur','Fazilpur Jharsa','Fazilpur','Tikri','Tigra','Kheri Daula','Kherki Daula','Kherki Majra','Hayatpur','Bajghera','Bhangrola','Begampur Khatola','Budhera','Gadauli Khurd','Gadauli Kalan','Gurgaon Rural','Palra','Darbaripur','Nangli Umarpur','Nangli Sakrawati','Wazirabad Village','Ghasola','Raisina','Sakatpur','Bandhwari','Sohna','Sohna Rural','Kukrola','Lakhnaula','Manesar','IMT Manesar','Kasan','Naharpur Rupa','Shikohpur','Baliawas','Abheypur','Moulsari','Sultanpur','Kherki Majra Dhankot','Farrukhnagar','Hailakandi','Garhi Harsaru Railway Colony','Pawla','Mankrola','Babupur','Basai Dhankot','Naurangpur','Naurangpur Road','Kherki Daula Village','Baliawas Road','Pachgaon','Aliyar','Bhora Kalan','Bhora Khurd','Binola','Bilaspur','Kukrola Road','Panchgaon','Khor','Sampka','Chandu','Dharampur','Dharuhera Border','Kherki Majra','Sihi','Tikri Kalan','Sector 29','Sector 31','Sector 40','Sector 43','Sector 46','Sector 49','Sector 50','Sector 51','Sector 52','Sector 53','Sector 54','Sector 55','Sector 56','Sector 57','Sector 58','Sector 59','Sector 60','Sector 61','Sector 62','Sector 63','Sector 64','Sector 65','Sector 66','Sector 67','Sector 68','Sector 69','Sector 70','Sector 70A','Sector 71','Sector 72','Sector 73','Sector 74','Sector 74A','Sector 75','Sector 75A','Sector 76','Sector 77','Sector 78','Sector 79','Sector 80','Sector 81','Sector 82','Sector 82A','Sector 83','Sector 84','Sector 85','Sector 86','Sector 87','Sector 88','Sector 88A','Sector 89','Sector 89A','Sector 90','Sector 91','Sector 92','Sector 93','Sector 93A','Sector 94','Sector 95','Sector 95A','Sector 96','Sector 97','Sector 98','Sector 99','Sector 100','Sector 101','Sector 102','Sector 102A','Sector 103','Sector 104','Sector 105','Sector 106','Sector 107','Sector 108','Sector 109','Sector 110','Sector 111','Sector 112','Sector 113','Sector 114','Sector 115'
];
const projectSeed=[
['DLF Privana North','Sector 76-77','Residential Flat','DLF','New Gurgaon','Approx. 116 acres','Premium high-rise residential community with landscaped greens, clubhouse and strong connectivity to NH-48 and SPR.'],
['DLF Privana South','Sector 76-77','Residential Flat','DLF','New Gurgaon','Approx. 25 acres','Premium residential development positioned around New Gurgaon’s emerging growth corridor.'],
['DLF Garden City Enclave','New Gurgaon','Residential Plot','DLF','New Gurgaon','Large township precinct','Plotted development concept with established DLF township ecosystem and road connectivity.'],
['Godrej Aristocrat','Sector 49','Residential Flat','Godrej Properties','Golf Course Extension Road','Approx. 9 acres','Luxury residential project with premium apartments, clubhouse amenities and access to major Gurgaon corridors.'],
['Godrej Vistas','Gurgaon','Residential Flat','Godrej Properties','Gurgaon','Project-specific','Premium urban residential offering; verify current inventory and sanctioned specifications before publishing transaction details.'],
['Whiteland The Aspen','Sector 76','Residential Flat','Whiteland Corporation','New Gurgaon','Approx. 12.3 acres','Luxury high-rise residences with clubhouse-led lifestyle amenities and New Gurgaon connectivity.'],
['Smartworld The Edition','Sector 66','Residential Flat','Smartworld Developers','Golf Course Extension Road','Approx. 5 acres','Premium residential development near Golf Course Extension Road with lifestyle amenities.'],
['Elan The Emperor','Sector 106','Residential Flat','Elan Group','Dwarka Expressway','Approx. 7.5 acres','Luxury high-rise residential development along Dwarka Expressway.'],
['Elan Town Centre','Sector 67','Commercial','Elan Group','Golf Course Extension Road','Approx. 4.5 acres','Mixed-use commercial destination with retail, food and entertainment components.'],
['Tulip Monsella','Sector 53','Residential Flat','Tulip Infratech','Golf Course Road','Approx. 12 acres','Premium high-rise residential community near Golf Course Road.'],
['Tulip Leaf','Sector 69','Residential Flat','Tulip Infratech','Sohna Road','Approx. 10 acres','Residential development positioned on the Sohna Road growth corridor.'],
['Signature Global City','Dwarka Expressway / New Gurgaon','Builder Floor','Signature Global','Dwarka Expressway','Multiple phases','Low-rise independent floor communities across New Gurgaon with gated amenities and road connectivity.'],
['M3M Golf Estate','Sector 65','Residential Flat','M3M Group','Golf Course Extension Road','Approx. 73 acres','Large luxury residential development with golf-oriented planning, premium towers and extensive amenities.'],
['M3M Golf Hills','Sector 79','Residential Flat','M3M Group','New Gurgaon','Approx. 56 acres','Luxury residential development on the New Gurgaon growth corridor.'],
['M3M Crown','Sector 111','Residential Flat','M3M Group','Dwarka Expressway','Approx. 73 acres','Premium residential community near Dwarka Expressway; verify phase-specific inventory.'],
['M3M Merlin','Sector 67','Residential Flat','M3M Group','Golf Course Extension Road','Approx. 12 acres','Premium residential development in the Golf Course Extension Road belt.'],
['Emaar Palm Gardens','Sector 83','Residential Flat','Emaar India','New Gurgaon','Approx. 29 acres','Established residential community in New Gurgaon with extensive internal amenities.'],
['Emaar Palm Heights','Sector 77','Residential Flat','Emaar India','New Gurgaon','Approx. 12 acres','High-rise residential project in the New Gurgaon corridor.'],
['Ireo Grand Arch','Sector 58','Residential Flat','Ireo','Golf Course Road','Approx. 20 acres','Large-format premium residential community near Golf Course Road.'],
['Paras Quartier','Gwal Pahari','Residential Flat','Paras Buildtech','Gurgaon-Faridabad Road','Approx. 10 acres','Luxury residential development on the Gwal Pahari / Faridabad-Gurgaon corridor.'],
['ATS Kocoon','Sector 109','Residential Flat','ATS Infrastructure','Dwarka Expressway','Approx. 11 acres','Residential community in the Dwarka Expressway corridor.'],
['BPTP Park Prime','Sector 66','Residential Flat','BPTP','Golf Course Extension Road','Approx. 20 acres','Established residential community with connectivity to Golf Course Extension Road.'],
['Hero Homes','Sector 104','Residential Flat','Hero Realty','Dwarka Expressway','Approx. 11 acres','Residential community positioned on the Dwarka Expressway corridor.'],
['Ashiana Amarah','Sector 93','Residential Flat','Ashiana Housing','New Gurgaon','Approx. 22 acres','Family-oriented residential community in New Gurgaon.'],
['ROF Atulyas','Sector 93','Residential Flat','ROF Group','New Gurgaon','Approx. 5 acres','Affordable/premium residential project in New Gurgaon.'],
['Pioneer Park','Sector 61','Residential Flat','Pioneer Urban','Golf Course Extension Road','Approx. 75 acres','Large residential development in the established Golf Course Extension Road belt.'],
['Spaze Corporate Park','Sector 69','Office Space','Spaze Group','Sohna Road','Approx. 10 acres','Commercial office destination on Sohna Road.'],
['AIPL Autograph','Sector 66','Office Space','AIPL','Golf Course Extension Road','Approx. 5 acres','Premium office destination on Golf Course Extension Road.'],
['AIPL Joy Street','Sector 66','Retail / Food Court','AIPL','Golf Course Extension Road','Approx. 2 acres','Retail and high-street commercial destination with food and lifestyle offerings.'],
['M3M Urbana','Sector 67','Retail / Office','M3M Group','Golf Course Extension Road','Approx. 6 acres','Mixed-use commercial destination with retail, office and hospitality components.'],
['Worldmark Gurgaon','Sector 65','Retail / Office','Emaar India','Golf Course Extension Road','Approx. 6 acres','Premium commercial destination with office, retail and dining uses.']
];
const propertySchemas={
  'Residential Flat':['project','tower','unit','floor','bhk','size','parking','facing','possession','demand'],
  'Luxury Floor / Builder Floor':['project','block','floor','bhk','unit','size','plotSize','parking','facing','construction','demand'],
  'Villa':['project','villaNo','bhk','size','plotSize','parking','facing','possession','demand'],
  'Plot / Residential Land':['plotNo','plotSize','frontage','roadWidth','facing','corner','landUse','demand'],
  'Retail Shop':['project','shopNo','floor','size','frontage','ceilingHeight','parking','possession','demand'],
  'Showroom':['project','unit','floor','size','frontage','roadWidth','parking','ceilingHeight','demand'],
  'Food Court':['project','unit','floor','size','frontage','powerLoad','fnbUse','possession','demand'],
  'Office Space':['project','tower','unit','floor','size','workstations','parking','possession','demand'],
  'Industrial Land':['industrialArea','plotNo','plotSize','frontage','roadWidth','zoning','powerLoad','water','demand'],
  'Agricultural Land':['village','khasraNo','landArea','frontage','roadWidth','irrigation','approachRoad','landUse','demand'],
  'Farmhouse':['village','farmName','landArea','builtUpArea','bedrooms','roadWidth','water','power','demand'],
  'Warehouse':['project','plotSize','builtUpArea','clearHeight','dockDoors','powerLoad','roadWidth','parking','demand'],
  'PG / Rental':['project','roomType','beds','size','floor','furnishing','rent','securityDeposit','availability'],
  'Commercial Property':['project','unit','floor','size','frontage','parking','use','possession','demand'],
  'Other':['size','floor','unit','description','demand']
};
const propertyFieldMeta={
 project:['Project / building name','text'],tower:['Tower / Block','text'],unit:['Unit / shop / office no.','text'],floor:['Floor','text'],bhk:['Configuration','text'],size:['Super / carpet / built-up size','text'],parking:['Parking details','text'],facing:['Facing','text'],possession:['Possession / availability','text'],demand:['Demand / price (₹)','number'],
 block:['Block','text'],plotSize:['Plot size','text'],construction:['Construction / age','text'],villaNo:['Villa no.','text'],plotNo:['Plot no.','text'],frontage:['Frontage','text'],roadWidth:['Road width','text'],corner:['Corner plot?','text'],landUse:['Land use / zoning','text'],shopNo:['Shop no.','text'],ceilingHeight:['Ceiling height','text'],powerLoad:['Power load','text'],fnbUse:['F&B / food-court use','text'],workstations:['Workstations','text'],industrialArea:['Industrial area / estate','text'],zoning:['Industrial zoning','text'],water:['Water arrangement','text'],irrigation:['Irrigation','text'],village:['Village','text'],khasraNo:['Khasra / survey no.','text'],landArea:['Land area','text'],approachRoad:['Approach road','text'],farmName:['Farmhouse name','text'],builtUpArea:['Built-up area','text'],bedrooms:['Bedrooms','text'],power:['Power connection','text'],clearHeight:['Clear height','text'],dockDoors:['Dock / loading doors','text'],roomType:['Room type','text'],beds:['Beds','text'],furnishing:['Furnishing','text'],rent:['Monthly rent (₹)','number'],securityDeposit:['Security deposit (₹)','number'],availability:['Availability','text'],use:['Permitted / current use','text'],description:['Additional details','text']
};
// Project metadata is kept separate from the location master list. Missing live facts are deliberately marked for verification rather than fabricated.
// Expanded Gurgaon project directory. Project facts are separated from location names; unverified fields remain explicitly marked.
projectSeed.push(
 ['DLF The Arbour','Sector 63','Residential Flat','DLF','Golf Course Extension Road','Approx. 25 acres','Luxury high-rise residential development.'],
 ['DLF The Dahlias','Sector 54','Residential Flat','DLF','Golf Course Road','Approx. 17.5 acres','Ultra-luxury high-rise residential development.'],
 ['DLF The Camellias','Sector 42','Residential Flat','DLF','Golf Course Road','Approx. 22 acres','Ultra-luxury residential development.'],
 ['DLF The Magnolias','Sector 42','Residential Flat','DLF','Golf Course Road','Approx. 25 acres','Luxury residential development.'],
 ['DLF The Crest','Sector 54','Residential Flat','DLF','Golf Course Road','Approx. 27 acres','Premium high-rise residential community.'],
 ['DLF Park Place','Sector 54','Residential Flat','DLF','Golf Course Road','Approx. 15 acres','Established premium residential community.'],
 ['DLF The Belaire','Sector 54','Residential Flat','DLF','Golf Course Road','Approx. 10 acres','Premium high-rise residential community.'],
 ['DLF The Ultima','Sector 81','Residential Flat','DLF','New Gurgaon','Approx. 22 acres','High-rise residential development.'],
 ['DLF New Town Heights','Sector 90','Residential Flat','DLF','New Gurgaon','Approx. 31 acres','Large residential community.'],
 ['DLF Alameda','Sector 73','Villa','DLF','Golf Course Extension Road','Approx. 30 acres','Low-rise villa / floor residential community.'],
 ['DLF City Court','Sector 24','Office Space','DLF','MG Road','Commercial project','Commercial office destination.'],
 ['Godrej Habitat','Sector 79','Residential Flat','Godrej Properties','New Gurgaon','Approx. 7 acres','Residential development.'],
 ['Godrej Prive','Sector 106','Residential Flat','Godrej Properties','Dwarka Expressway','Approx. 15 acres','Premium residential development.'],
 ['Godrej Vriksha','Sector 103','Residential Flat','Godrej Properties','Dwarka Expressway','Approx. 15 acres','Premium residential development.'],
 ['Godrej Aristocrat','Sector 49','Residential Flat','Godrej Properties','Golf Course Extension Road','Approx. 9 acres','Luxury residential development.'],
 ['Signature Global Park','Sector 36 Sohna','Luxury Floor / Builder Floor','Signature Global','Sohna','Approx. 20 acres','Low-rise floor community in Sohna.'],
 ['Signature Global City 81','Sector 81','Luxury Floor / Builder Floor','Signature Global','New Gurgaon','Multiple acres / phases','Low-rise floor development.'],
 ['Signature Global City 79B','Sector 79B','Luxury Floor / Builder Floor','Signature Global','New Gurgaon','Multiple acres / phases','Low-rise floor development.'],
 ['Signature Global Solera','Sector 107','Luxury Floor / Builder Floor','Signature Global','Dwarka Expressway','Approx. 10 acres','Affordable housing / low-rise community.'],
 ['Signature Global The Millennia','Sector 37D','Residential Flat','Signature Global','Dwarka Expressway','Approx. 12 acres','Residential development.'],
 ['Smartworld Orchard','Sector 61','Residential Flat','Smartworld Developers','Golf Course Extension Road','Approx. 20 acres','Residential community.'],
 ['Smartworld Gems','Sector 89','Residential Flat','Smartworld Developers','New Gurgaon','Approx. 7 acres','Residential development.'],
 ['Smartworld One DXP','Sector 113','Residential Flat','Smartworld Developers','Dwarka Expressway','Multiple acres','High-rise residential development.'],
 ['M3M Heights','Sector 65','Residential Flat','M3M Group','Golf Course Extension Road','Approx. 12 acres','High-rise residential development.'],
 ['M3M Mansion','Sector 113','Residential Flat','M3M Group','Dwarka Expressway','Multiple acres','Premium residential development.'],
 ['M3M Latitude','Sector 65','Residential Flat','M3M Group','Golf Course Extension Road','Approx. 5 acres','Luxury residential development.'],
 ['M3M Sky Lofts','Sector 71','Residential Flat','M3M Group','Sohna Road','Approx. 5 acres','Residential / loft-style development.'],
 ['M3M IFC','Sector 66','Office Space','M3M Group','Golf Course Extension Road','Approx. 3 acres','International financial / commercial centre.'],
 ['M3M Broadway','Sector 71','Retail / Food Court','M3M Group','Sohna Road','Approx. 6 acres','Retail, dining and entertainment destination.'],
 ['M3M Route65','Sector 65','Retail / Food Court','M3M Group','Golf Course Extension Road','Commercial development','High-street commercial destination.'],
 ['M3M Tee Point','Sector 65','Retail / Food Court','M3M Group','Golf Course Extension Road','Commercial development','Retail / dining destination.'],
 ['Emaar Urban Oasis','Sector 62','Residential Flat','Emaar India','Golf Course Extension Road','Approx. 14 acres','Residential development.'],
 ['Emaar Marbella','Sector 66','Villa','Emaar India','Golf Course Extension Road','Approx. 75 acres','Luxury villa community.'],
 ['Emaar Palm Terraces','Sector 66','Residential Flat','Emaar India','Golf Course Extension Road','Approx. 20 acres','Residential community.'],
 ['Emaar Palm Heights','Sector 77','Residential Flat','Emaar India','New Gurgaon','Approx. 12 acres','High-rise residential development.'],
 ['Sobha City','Sector 108','Residential Flat','Sobha','Dwarka Expressway','Approx. 39 acres','Large residential community.'],
 ['Sobha International City','Sector 109','Villa','Sobha','Dwarka Expressway','Approx. 150 acres','Large luxury villa community.'],
 ['Sobha Altus','Sector 106','Residential Flat','Sobha','Dwarka Expressway','Approx. 12 acres','Premium residential development.'],
 ['Sobha Aranya','Sector 36 Sohna','Residential Flat','Sobha','Sohna','Approx. 31 acres','Premium residential development.'],
 ['Conscient Habitat 78','Sector 78','Residential Flat','Conscient','New Gurgaon','Approx. 10 acres','Residential development.'],
 ['Conscient One','Sector 109','Residential Flat','Conscient','Dwarka Expressway','Multiple acres','Residential development.'],
 ['Conscient Hines Elevate','Sector 59','Residential Flat','Conscient Hines','Golf Course Extension Road','Approx. 7 acres','Premium residential development.'],
 ['Hero Homes','Sector 104','Residential Flat','Hero Realty','Dwarka Expressway','Approx. 11 acres','Residential development.'],
 ['Ashiana Amarah','Sector 93','Residential Flat','Ashiana Housing','New Gurgaon','Approx. 22 acres','Family-oriented residential community.'],
 ['Ashiana Aaroh','Sector 80','Residential Flat','Ashiana Housing','New Gurgaon','Residential development','Residential community.'],
 ['ROF Ananda','Sector 95','Luxury Floor / Builder Floor','ROF Group','New Gurgaon','Approx. 5 acres','Low-rise residential development.'],
 ['ROF Normanton Park','Sector 36 Sohna','Luxury Floor / Builder Floor','ROF Group','Sohna','Residential development','Low-rise residential development.'],
 ['ROF Atulyas','Sector 93','Residential Flat','ROF Group','New Gurgaon','Approx. 5 acres','Residential development.'],
 ['ATS Kocoon','Sector 109','Residential Flat','ATS Infrastructure','Dwarka Expressway','Approx. 11 acres','Residential community.'],
 ['ATS Triumph','Sector 104','Residential Flat','ATS Infrastructure','Dwarka Expressway','Residential development','Residential community.'],
 ['BPTP Park Prime','Sector 66','Residential Flat','BPTP','Golf Course Extension Road','Approx. 20 acres','Established residential community.'],
 ['BPTP Astaire Gardens','Sector 70A','Villa','BPTP','Golf Course Extension Road','Large township','Villa / floor residential community.'],
 ['Pioneer Park','Sector 61','Residential Flat','Pioneer Urban','Golf Course Extension Road','Approx. 75 acres','Large residential development.'],
 ['Ireo Victory Valley','Sector 67','Residential Flat','Ireo','Golf Course Extension Road','Approx. 25 acres','Premium residential development.'],
 ['Paras Florett','Sector 59','Residential Flat','Paras Buildtech','Golf Course Extension Road','Residential development','Residential community.'],
 ['Spaze iTech Park','Sector 49','Office Space','Spaze Group','Sohna Road','Commercial development','Office / commercial destination.'],
 ['Spaze Corporate Park','Sector 69','Office Space','Spaze Group','Sohna Road','Approx. 10 acres','Commercial office destination.'],
 ['Reach Airia','Sector 68','Commercial Property','Reach Group','Sohna Road','Commercial development','Mixed commercial destination.'],
 ['Reach 3 Roads','Sector 70','Retail / Food Court','Reach Group','Sohna Road','Commercial development','Retail / dining destination.'],
 ['Bestech Chambers','Sector 44','Office Space','Bestech Group','Golf Course Road','Commercial development','Office destination.'],
 ['Bestech Park View Grand Spa','Sector 81','Residential Flat','Bestech Group','New Gurgaon','Residential development','Residential community.'],
 ['Suncity Avenue 76','Sector 76','Residential Flat','Suncity Projects','New Gurgaon','Residential development','Residential community.'],
 ['Suncity Vatsal Valley','Sector 2 Sohna','Residential Flat','Suncity Projects','Sohna','Large development','Residential township.'],
 ['Tulip Lemon','Sector 69','Residential Flat','Tulip Infratech','Sohna Road','Approx. 10 acres','Residential development.'],
 ['Tulip Violet','Sector 69','Residential Flat','Tulip Infratech','Sohna Road','Approx. 10 acres','Residential development.'],
 ['Tulip Ivory','Sector 70','Residential Flat','Tulip Infratech','Sohna Road','Approx. 10 acres','Residential development.'],
 ['Tulip Petals','Sector 89','Residential Flat','Tulip Infratech','New Gurgaon','Residential development','Residential community.'],
 ['Elan The Emperor','Sector 106','Residential Flat','Elan Group','Dwarka Expressway','Approx. 7.5 acres','Luxury high-rise residential development.'],
 ['Elan Town Centre','Sector 67','Commercial Property','Elan Group','Golf Course Extension Road','Approx. 4.5 acres','Mixed-use commercial destination.'],
 ['Central Park Flower Valley','Sector 32 Sohna','Residential Flat','Central Park','Sohna','Large township','Integrated residential township.'],
 ['Central Park Resorts','Sector 48','Residential Flat','Central Park','Sohna Road','Large development','Luxury residential community.'],
 ['Trump Tower Gurgaon','Sector 65','Residential Flat','Trump / Tribeca','Golf Course Extension Road','Approx. 1.25 acres','Ultra-luxury residential tower.'],
 ['Paras Quartier','Gwal Pahari','Residential Flat','Paras Buildtech','Gurgaon-Faridabad Road','Approx. 10 acres','Luxury residential development.'],
 ['The Grand Hyatt Residences Gurgaon','Sector 58','Residential Flat','Hyatt / Developer partner','Golf Course Road','Project-specific','Luxury branded residences; verify current inventory.']
);
const projectMeta={
  'DLF Privana North':{land:'Approx. 116 acres',towers:'Multiple towers / phase-wise',floors:'High-rise; phase-specific',sizes:'3/4 BHK; verify current inventory',price:'Current price on request / verify official inventory'},
  'DLF Privana South':{land:'Approx. 25 acres',towers:'Multiple towers / phase-wise',floors:'High-rise; phase-specific',sizes:'4 BHK / premium residences; verify current inventory',price:'Current price on request / verify official inventory'},
  'Godrej Aristocrat':{land:'Approx. 9 acres',towers:'Multiple towers',floors:'High-rise; phase-specific',sizes:'3/4 BHK; verify current inventory',price:'Current price on request / verify official inventory'},
  'Whiteland The Aspen':{land:'Approx. 12.3 acres',towers:'Multiple towers',floors:'High-rise; phase-specific',sizes:'3/4 BHK; verify current inventory',price:'Current price on request / verify official inventory'},
  'Smartworld The Edition':{land:'Approx. 5 acres',towers:'Multiple towers',floors:'High-rise; phase-specific',sizes:'2/3/4 BHK; verify current inventory',price:'Current price on request / verify official inventory'},
  'Elan The Emperor':{land:'Approx. 7.5 acres',towers:'Multiple towers',floors:'High-rise; phase-specific',sizes:'3/4 BHK; verify current inventory',price:'Current price on request / verify official inventory'},
  'M3M Golf Estate':{land:'Approx. 73 acres',towers:'Multiple residential towers',floors:'High-rise; phase-specific',sizes:'3/4/5 BHK; verify current inventory',price:'Current price on request / verify official inventory'},
  'M3M Golf Hills':{land:'Approx. 56 acres',towers:'Multiple towers',floors:'High-rise; phase-specific',sizes:'2.5/3.5/4 BHK; verify current inventory',price:'Current price on request / verify official inventory'},
  'M3M Crown':{land:'Approx. 73 acres',towers:'Multiple towers',floors:'High-rise; phase-specific',sizes:'2.5/3.5/4 BHK; verify current inventory',price:'Current price on request / verify official inventory'},
  'M3M Merlin':{land:'Approx. 12 acres',towers:'Multiple towers',floors:'High-rise; phase-specific',sizes:'3/4 BHK; verify current inventory',price:'Current price on request / verify official inventory'},
  'Emaar Palm Gardens':{land:'Approx. 29 acres',towers:'Multiple towers',floors:'High-rise; phase-specific',sizes:'2/3/4 BHK; verify current inventory',price:'Current price on request / verify official inventory'},
  'Ireo Grand Arch':{land:'Approx. 20 acres',towers:'Multiple towers',floors:'High-rise; phase-specific',sizes:'3/4 BHK; verify current inventory',price:'Current price on request / verify official inventory'},
  'Paras Quartier':{land:'Approx. 10 acres',towers:'Multiple towers',floors:'High-rise; phase-specific',sizes:'4/5 BHK; verify current inventory',price:'Current price on request / verify official inventory'},
  'AIPL Autograph':{land:'Approx. 5 acres',towers:'Commercial blocks',floors:'High-rise commercial; verify official disclosure',sizes:'Office suites / floor plates; verify current inventory',price:'Current price on request / verify official inventory'},
  'AIPL Joy Street':{land:'Approx. 2 acres',towers:'Commercial blocks',floors:'Low/mid-rise commercial; verify official disclosure',sizes:'Retail / F&B units; verify current inventory',price:'Current price on request / verify official inventory'},
  'M3M Urbana':{land:'Approx. 6 acres',towers:'Commercial blocks',floors:'Commercial; phase-specific',sizes:'Retail / office / hospitality; verify current inventory',price:'Current price on request / verify official inventory'},
  'Worldmark Gurgaon':{land:'Approx. 6 acres',towers:'Commercial blocks',floors:'Commercial; phase-specific',sizes:'Retail / office / dining; verify current inventory',price:'Current price on request / verify official inventory'}
};
projectSeed.forEach(p=>{p[7]=projectMeta[p[0]]||{land:p[5]||'Verify official disclosure',towers:'Verify official project disclosure',floors:'Verify official project disclosure',sizes:'Verify current inventory',price:'On request / verify current price'};});
const projectImages={
'Commercial':'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=85',
'Residential Flat':'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85',
'Builder Floor':'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1600&q=85',
'Residential Plot':'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=85',
'Default':'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85'
};
function wa(text='Hello Moneyland Corporation, I am interested in a property.'){return `${WHATS}?text=${encodeURIComponent(text)}`}
function money(n){return n?`₹${Number(n).toLocaleString('en-IN')}`:'On Request'}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fillSelect(id,arr,placeholder='Select'){const e=document.getElementById(id);if(!e)return;e.innerHTML=`<option value="">${placeholder}</option>`+[...new Set(arr)].sort((a,b)=>a.localeCompare(b)).map(x=>`<option>${esc(x)}</option>`).join('')}
function renderHeader(){const e=document.querySelector('[data-ml-header]');if(!e)return;e.innerHTML=`<header class="nav"><a class="brand" href="index.html"><span class="brand-logo"><img src="assets/logo-placeholder.svg" alt="Moneyland Corporation"></span></a><nav><a href="index.html">Home</a><a href="properties.html">Properties</a><a href="map.html">Gurgaon Map</a><a href="list-property.html">Post Your Property</a><a href="about.html">About</a><a href="career.html">Career</a><a href="contact.html">Contact</a><a href="login.html">Login / Register</a></nav><a class="nav-cta" href="${wa('Hello Moneyland Corporation, I want to enquire about a property.')}" target="_blank">WhatsApp</a><button class="menu" onclick="document.querySelector('.nav nav').classList.toggle('open')">☰</button></header>`}
function renderFooter(){const e=document.querySelector('[data-ml-footer]');if(!e)return;e.innerHTML=`<footer><div class="footer-grid"><div><div class="brand"><span class="brand-logo"><img src="assets/logo-placeholder.svg" alt="Moneyland Corporation"></span></div><p>${ML.tagline}</p><a class="wa" target="_blank" href="${wa()}">Chat on WhatsApp</a></div><div><h4>Explore</h4><a href="properties.html">Properties</a><a href="map.html">Gurgaon Map</a><a href="list-property.html">Post Your Property</a><a href="subscription.html">Lifetime Brokerage Plan</a></div><div><h4>Company</h4><a href="about.html">About</a><a href="career.html">Career / Jobs</a><a href="contact.html">Contact</a><a href="admin.html">Admin</a></div><div><h4>Office</h4><p>${ML.address}</p><p>GSTIN: ${ML.gst}</p><p>RERA: ${ML.rera}</p><a href="mailto:${ML.email}">${ML.email}</a></div></div><div class="copyright">© ${new Date().getFullYear()} ${ML.name}. All rights reserved.</div></footer>`}
function init(){renderHeader();renderFooter();fillSelect('location',[...sectors,...localities],'All Gurgaon locations');fillSelect('category',categories.map(x=>x[0]),'All property types');fillSelect('propertyType',categories.map(x=>x[0]),'Select property type');fillSelect('area',[...sectors,...localities],'Select Gurgaon location');document.getElementById('propertyType')?.addEventListener('change',renderConditionalFields);renderConditionalFields();renderProjects();renderListings();initMap();}
function getListings(){try{return JSON.parse(localStorage.getItem('ml_listings')||'[]')}catch{return[]}}
function saveListing(l){const a=getListings();a.unshift(l);localStorage.setItem('ml_listings',JSON.stringify(a));return l}
function renderProjects(){const box=document.querySelector('#projectGrid');if(!box)return;const q=(document.querySelector('#projectSearch')?.value||'').toLowerCase();const loc=document.querySelector('#location')?.value||'';const cat=document.querySelector('#category')?.value||'';const arr=projectSeed.filter(p=>(!q||p.slice(0,7).join(' ').toLowerCase().includes(q))&&(!loc||p[1].includes(loc))&&(!cat||p[2].includes(cat))).slice(0,160);box.innerHTML=arr.map((p,i)=>`<article class="project-card"><img src="${projectImages[p[2]]||projectImages.Default}" alt="${esc(p[0])}"><div class="project-body"><span class="pill">${esc(p[2])}</span><h3>${esc(p[0])}</h3><p class="muted">${esc(p[1])} · ${esc(p[3])}</p><p>${esc(p[6])}</p><div class="mini-stats"><span>Land parcel<br><b>${esc(p[7]?.land||p[5])}</b></span><span>Location<br><b>${esc(p[1])}</b></span><span>Sizes<br><b>${esc(p[7]?.sizes||'Verify')}</b></span></div><a class="btn secondary" href="property.html?project=${encodeURIComponent(p[0])}">View project</a></div></article>`).join('')||`<div class="empty">No matching project. <a href="${wa('Hello Moneyland Corporation, I want help finding a Gurgaon property.')}" target="_blank">Ask us on WhatsApp</a>.</div>`}
function renderListings(){const box=document.querySelector('#listingGrid');if(!box)return;let a=getListings().filter(x=>x.status==='approved');if(!a.length){box.innerHTML='<div class="empty">No owner listing is publicly approved yet. Verified owners can <a href="list-property.html">post a property</a>.</div>';return}box.innerHTML=a.map(l=>`<article class="listing-card"><img src="${l.photos?.[0]||projectImages.Default}"><div><span class="pill">Moneyland Verified</span><h3>${esc(l.title)}</h3><p>${esc(l.type)} · ${esc(l.location)}</p><div class="price">${money(l.demand)}</div><a class="btn" target="_blank" href="${wa(`Hello Moneyland Corporation, I am interested in ${l.title} at ${l.location}. Listing ID: ${l.id}`)}">Enquire on WhatsApp</a></div></article>`).join('')}
function renderConditionalFields(){const type=document.getElementById('propertyType')?.value;const box=document.getElementById('conditionalFields');if(!box)return;const keys=propertySchemas[type]||[];box.innerHTML=keys.map(k=>{const m=propertyFieldMeta[k]||[k,'text'];const label=esc(m[0]);const input=m[1]==='number'?`<input class="input" name="${k}" type="number" step="any">`:`<input class="input" name="${k}" class="input">`;return `<div class="field"><label>${label}</label>${input}</div>`}).join('');}
function submitPost(e){e.preventDefault();const f=new FormData(e.target);const photos=[...document.querySelector('#photos').files].slice(0,50).map(x=>URL.createObjectURL(x));const type=f.get('type');const details={};(propertySchemas[type]||[]).forEach(k=>details[k]=f.get(k)||'');const l={id:'ML-'+Date.now(),title:f.get('title'),type,location:f.get('location'),details,description:f.get('description')||details.description||'',photos,status:'pending_verification',createdAt:new Date().toISOString(),ownerName:f.get('ownerName'),ownerAadhaarLast4:(f.get('aadhaar')||'').slice(-4)};saveListing(l);alert('Property submitted. Moneyland Corporation verification is now required before the listing becomes public.');location.href='dashboard.html'}
function initMap(){const el=document.getElementById('gurgaonMap');if(!el||!window.L)return;const map=L.map(el,{scrollWheelZoom:true}).setView([28.4595,77.0266],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);const points=[['Cyber City',28.4946,77.0888],['Golf Course Road',28.4517,77.1013],['Golf Course Extension Road',28.413,77.073],['Dwarka Expressway',28.499,76.987],['Sohna Road',28.394,77.042],['MG Road',28.479,77.092],['New Gurgaon',28.42,76.99],['IMT Manesar',28.351,76.936],['Sohna',28.247,77.065],['M3M 65th Avenue',28.416,77.057]];points.forEach(p=>L.marker([p[1],p[2]]).addTo(map).bindPopup(`<b>${p[0]}</b><br><a target="_blank" href="${wa(`Hello Moneyland Corporation, I want properties in ${p[0]}.`)}">Enquire on WhatsApp</a>`));window.mlMap=map}
function projectDetail(){const name=new URLSearchParams(location.search).get('project');const p=projectSeed.find(x=>x[0]===name);const box=document.querySelector('#projectDetail');if(!box||!p)return;if(document.title)document.title=`${p[0]} | ${ML.name}`;const d=p[7]||{};box.innerHTML=`<div class="detail-media"><img src="${projectImages[p[2]]||projectImages.Default}"><span class="pill">${esc(p[2])} · Details should be checked against current official/RERA disclosures</span></div><div class="detail-copy"><span class="eyebrow">${esc(p[4])}</span><h1>${esc(p[0])}</h1><p class="lead">${esc(p[6])}</p><div class="facts"><div><small>Property type</small><b>${esc(p[2])}</b></div><div><small>Developer</small><b>${esc(p[3])}</b></div><div><small>Total land / parcel</small><b>${esc(d.land||p[5]||'Not published')}</b></div><div><small>Towers / blocks</small><b>${esc(d.towers||'Verify with official project disclosure')}</b></div><div><small>Building height</small><b>${esc(d.floors||'Verify with official project disclosure')}</b></div><div><small>Available sizes</small><b>${esc(d.sizes||'Verify current inventory')}</b></div><div><small>Tentative pricing</small><b>${esc(d.price||'On request / verify current price')}</b></div><div><small>Project location</small><b>${esc(p[1])}</b></div></div><div class="notice"><b>Moneyland data policy:</b> project facts are shown only when verified or marked for verification. Final price, inventory, approvals, tower/floor count and possession must be checked before any transaction.</div><div class="action-row"><a class="btn" target="_blank" href="${wa(`Hello Moneyland Corporation, I am interested in ${p[0]} in ${p[1]}. Please share verified current inventory.`)}">Contact Moneyland</a><button class="btn secondary" onclick="openBid('${esc(p[0])}','buy')">Bid Your Offer</button></div></div>`}
function openBid(title,type='buy'){const token=type==='rent'?ML.bidRent:ML.bidBuy;const msg=`Bid access requires a ${money(token)} refundable security deposit for ${type==='rent'?'rent':'purchase'} bids. Login/register is required and the bid is subject to verification.`;const ok=confirm(msg+'\n\nContinue to connect with Moneyland Corporation?');if(ok)location.href=`login.html?next=${encodeURIComponent(location.href)}`}
function adminApprove(id){const a=getListings();const l=a.find(x=>x.id===id);if(!l)return;l.status='approved';saveAll(a);renderAdmin()}
function saveAll(a){localStorage.setItem('ml_listings',JSON.stringify(a))}
function renderAdmin(){const b=document.querySelector('#adminListings');if(!b)return;const a=getListings();b.innerHTML=a.length?a.map(l=>`<tr><td>${esc(l.id)}</td><td>${esc(l.title)}</td><td>${esc(l.type)}</td><td>${esc(l.location)}</td><td>${esc(l.status)}</td><td>${l.status!=='approved'?`<button class="small-btn" onclick="adminApprove('${l.id}')">Approve</button>`:'✓'}</td></tr>`).join(''):'<tr><td colspan="6">No owner submissions.</td></tr>'}
window.addEventListener('DOMContentLoaded',()=>{init();projectDetail();renderAdmin()});
