/* Moneyland Corporation - premium frontend layer
   Note: project facts that require live source verification are intentionally marked for verification.
*/
const ML={
  company:'Moneyland Corporation', phone:'8178593108', whatsapp:'https://wa.me/918178593108', email:'rrahmawat@gmail.com',
  gst:'06CKJPR5013B1ZH', rera:'RC/HARERA/GGM/4078/3673/2026/113',
  address:'R1/205, M3M 65th Avenue, Sector 65, Gurgaon, Gurugram, Haryana - 122018',
  website:'www.moneylandcorporation.com', tagline:'Gurgaon Ki Har Property, Sirf Ek Baar, Malik Se Direct'
};
const sectors=Array.from({length:115},(_,i)=>`Sector ${i+1}`);
const localities=[...sectors,'Sector 70A','Sector 81A','Sector 82A','Sector 88A','Sector 89A','Sector 90A','Sector 91A','Sector 92A','Sector 95A','Sector 96A','Sector 99A','Sector 100A','Sector 102A','Sector 103A','Sector 104A','Sector 105A','Sector 106A','Sector 107A','Sector 108A','Sector 109A','Sector 110A','Sector 111A','Sector 112A','Sector 113A','Sector 114A','Sector 115A','DLF Phase 1','DLF Phase 2','DLF Phase 3','DLF Phase 4','DLF Phase 5','DLF City','Golf Course Road','Golf Course Extension Road','MG Road','Sohna Road','Dwarka Expressway','New Gurgaon','Southern Peripheral Road','SPR','Northern Peripheral Road','NH-8','Nirvana Country','Sushant Lok 1','Sushant Lok 2','Sushant Lok 3','Palam Vihar','South City 1','South City 2','Malibu Town','M3M','Gwal Pahari','Faridabad Road','Manesar','IMT Manesar','Udyog Vihar','Cyber City','DLF Cyber City','Vatika Chowk','Badshahpur','Wazirabad','Sikanderpur','Shikohpur','Kherki Daula','Basai Road','Pataudi Road','New Palam Vihar','Rajendra Park','Sohna'];
const propertyTypes=['Flat / Apartment','Builder Floor','Independent Floor','Villa','Plot','Commercial Shop','Office Space','Warehouse','Showroom','Industrial Property','Independent House','Farm House'];

// Real project names commonly associated with Gurugram. Live inventory, land parcel, pricing and official imagery must be verified from the builder/RERA source before publication.
const rawProjects=[
['DLF','DLF Privana North','Sector 76–77','Flat / Apartment'],['DLF','DLF Privana South','Sector 76–77','Flat / Apartment'],['DLF','DLF The Arbour','Sector 63','Flat / Apartment'],['DLF','DLF The Grove','Sector 54','Flat / Apartment'],['DLF','DLF The Ultima','Sector 81','Flat / Apartment'],['DLF','DLF Park Place','Sector 54','Flat / Apartment'],['DLF','DLF The Crest','Sector 54','Flat / Apartment'],['DLF','DLF The Belaire','Sector 54','Flat / Apartment'],['DLF','DLF New Town Heights','Sector 90','Flat / Apartment'],['DLF','DLF Garden City Enclave','New Gurgaon','Villa'],['DLF','DLF The Camellias','Golf Course Road','Flat / Apartment'],['DLF','DLF The Magnolias','Golf Course Road','Flat / Apartment'],['DLF','DLF The Aralias','Golf Course Road','Flat / Apartment'],
['Godrej Properties','Godrej Aristocrat','Sector 49','Flat / Apartment'],['Godrej Properties','Godrej Vriksha','Sector 103','Flat / Apartment'],['Godrej Properties','Godrej Miraya','Sector 43','Flat / Apartment'],['Godrej Properties','Godrej Zenith','Sector 89','Flat / Apartment'],['Godrej Properties','Godrej Habitat','Sector 3','Flat / Apartment'],['Godrej Properties','Godrej Air','Sector 85','Flat / Apartment'],['Godrej Properties','Godrej Prive','Sector 106','Flat / Apartment'],['Godrej Properties','Godrej Summit','Sector 104','Flat / Apartment'],['Godrej Properties','Godrej Icon','Sector 88A','Flat / Apartment'],['Godrej Properties','Godrej Nature Plus','Sector 33','Flat / Apartment'],
['M3M','M3M Crown','Sector 111','Flat / Apartment'],['M3M','M3M Capital','Sector 113','Flat / Apartment'],['M3M','M3M Golf Estate','Sector 65','Flat / Apartment'],['M3M','M3M Mansion','Sector 113','Flat / Apartment'],['M3M','M3M Merlin','Sector 67','Flat / Apartment'],['M3M','M3M Latitude','Sector 65','Flat / Apartment'],['M3M','M3M Altitude','Sector 65','Flat / Apartment'],['M3M','M3M Antalya Hills','Sector 79','Flat / Apartment'],['M3M','M3M Golf Hills','Sector 79','Flat / Apartment'],['M3M','M3M Soulitude','Sector 89','Flat / Apartment'],['M3M','M3M Elements','Sector 67','Flat / Apartment'],['M3M','M3M 113 Market','Sector 113','Commercial Shop'],['M3M','M3M 114 Market','Sector 114','Commercial Shop'],
['Signature Global','Signature Global City 37D','Sector 37D','Builder Floor'],['Signature Global','Signature Global City 81','Sector 81','Builder Floor'],['Signature Global','Signature Global City 79B','Sector 79B','Builder Floor'],['Signature Global','Signature Global City 92','Sector 92','Builder Floor'],['Signature Global','Signature Global City 93','Sector 93','Builder Floor'],['Signature Global','Signature Global City 37','Sector 37','Builder Floor'],['Signature Global','Signature Global City 88A','Sector 88A','Builder Floor'],['Signature Global','Signature Global The Millennia','Sector 37D','Flat / Apartment'],['Signature Global','Signature Global Solera','Sector 107','Flat / Apartment'],['Signature Global','Signature Global Park','Sector 36 Sohna','Flat / Apartment'],['Signature Global','Signature Global Prime','Sector 63A','Flat / Apartment'],
['Smartworld Developers','Smartworld The Edition','Sector 66','Flat / Apartment'],['Smartworld Developers','Smartworld Gems','Sector 89','Flat / Apartment'],['Smartworld Developers','Smartworld Orchard','Sector 61','Flat / Apartment'],['Smartworld Developers','Smartworld One DXP','Dwarka Expressway','Flat / Apartment'],
['Whiteland','Whiteland The Aspen','Sector 76','Flat / Apartment'],['Whiteland','Whiteland The Aravalli','Sector 103','Flat / Apartment'],
['Elan Group','Elan The Emperor','Sector 106','Flat / Apartment'],['Elan Group','Elan The Presidential','Sector 106','Flat / Apartment'],['Elan Group','Elan The Miracles','Sector 84','Commercial Shop'],['Elan Group','Elan The Epic','Sector 106','Commercial Shop'],['Elan Group','Elan Town Centre','Sector 67','Commercial Shop'],['Elan Group','Elan Mark','Sector 106','Commercial Shop'],
['Sobha','Sobha City','Sector 108','Flat / Apartment'],['Sobha','Sobha International City','Sector 109','Villa'],['Sobha','Sobha Altus','Sector 106','Flat / Apartment'],['Sobha','Sobha Aranya','Sector 36 Sohna','Flat / Apartment'],['Sobha','Sobha Orbis','Sector 58','Flat / Apartment'],
['Tulip Infratech','Tulip Monsella','Golf Course Extension Road','Flat / Apartment'],['Tulip Infratech','Tulip Lemon','Sector 69','Flat / Apartment'],['Tulip Infratech','Tulip Violet','Sector 69','Flat / Apartment'],['Tulip Infratech','Tulip Ivory','Sector 70','Flat / Apartment'],['Tulip Infratech','Tulip Ace','Sector 89','Flat / Apartment'],['Tulip Infratech','Tulip Petals','Sector 89','Flat / Apartment'],['Tulip Infratech','Tulip White','Sector 69','Flat / Apartment'],['Tulip Infratech','Tulip Leaf','Golf Course Extension Road','Flat / Apartment'],
['Emaar India','Emaar Palm Gardens','Sector 83','Flat / Apartment'],['Emaar India','Emaar Palm Heights','Sector 77','Flat / Apartment'],['Emaar India','Emaar Urban Oasis','Sector 62','Flat / Apartment'],['Emaar India','Emaar Marbella','Sector 66','Villa'],['Emaar India','Emaar EBD 89','Sector 89','Commercial Shop'],
['Central Park','Central Park Resorts','Sector 48','Flat / Apartment'],['Central Park','Central Park Flower Valley','Sohna','Flat / Apartment'],['Central Park','Central Park Bellavista','Sohna','Flat / Apartment'],['Central Park','Central Park Clover Floors','Sector 32 Sohna','Builder Floor'],
['Mahindra Lifespaces','Mahindra Luminare','Sector 59','Flat / Apartment'],['Mahindra Lifespaces','Mahindra Aura','Sector 110A','Flat / Apartment'],
['ATS Homekraft','ATS Marigold','Sector 89A','Flat / Apartment'],['ATS Homekraft','ATS Triumph','Sector 104','Flat / Apartment'],['ATS Homekraft','ATS Kocoon','Sector 162A','Flat / Apartment'],['ATS Homekraft','Happy Trails','Sector 150','Flat / Apartment'],
['AIPL','AIPL Joy Street','Golf Course Extension Road','Commercial Shop'],['AIPL','AIPL Joy Central','Sector 65','Commercial Shop'],['AIPL','AIPL Autograph','Sector 66','Commercial Shop'],['AIPL','AIPL Zen Residences','Sector 70A','Flat / Apartment'],['AIPL','AIPL The Peaceful Homes','Sector 70A','Flat / Apartment'],
['Ashiana Housing','Ashiana Amarah','Sector 93','Flat / Apartment'],['Ashiana Housing','Ashiana Anmol','Sector 33 Sohna','Flat / Apartment'],
['Puri Constructions','Puri The Aravallis','Sector 61','Flat / Apartment'],['Puri Constructions','Puri Diplomatic Residences','Sector 111','Flat / Apartment'],['Puri Constructions','Puri The Prive','Sector 50','Flat / Apartment'],
['Ansal API','Ansal Esencia','Sector 67','Villa'],['Ansal API','Ansal Highland Park','Sector 103','Flat / Apartment'],['Ansal API','Ansal Harmony Homes','Sector 91','Flat / Apartment'],
['BPTP','BPTP Terra','Sector 37D','Flat / Apartment'],['BPTP','BPTP Amstoria','Sector 102','Villa'],['BPTP','BPTP Park Generations','Sector 37D','Flat / Apartment'],['BPTP','BPTP Park Serene','Sector 37D','Flat / Apartment'],
['Ireo','Ireo Grand Arch','Sector 58','Flat / Apartment'],['Ireo','Ireo Skyon','Sector 60','Flat / Apartment'],['Ireo','Ireo Victory Valley','Sector 67','Flat / Apartment'],
['Bestech','Bestech Park View Grand Spa','Sector 81','Flat / Apartment'],['Bestech','Bestech Park View Sanskruti','Sector 92','Flat / Apartment'],['Bestech','Bestech Park View Ananda','Sector 81','Flat / Apartment'],['Bestech','Bestech Altima','Sector 81','Flat / Apartment'],
['Conscient Infrastructure','Conscient Habitat','Sector 78','Flat / Apartment'],['Conscient Infrastructure','Conscient Hines Elevate','Sector 59','Flat / Apartment'],['Conscient Infrastructure','Conscient One','Sector 78','Flat / Apartment'],
['Raheja Developers','Raheja Vanya','Sector 99A','Flat / Apartment'],['Raheja Developers','Raheja Atharva','Sector 92','Flat / Apartment'],['Raheja Developers','Raheja Revanta','Sector 78','Flat / Apartment'],['Raheja Developers','Raheja Shilas','Sector 47','Flat / Apartment'],
['Vatika Group','Vatika Sovereign Park','Sector 99','Flat / Apartment'],['Vatika Group','Vatika India Next','Sector 83','Flat / Apartment'],['Vatika Group','Vatika Town Square','Sector 83','Commercial Shop'],['Vatika Group','Vatika INXT Emilia','Sector 83','Flat / Apartment']
];
const projects=rawProjects.map((p,i)=>({id:`project-${i+1}`,builder:p[0],name:p[1],loc:p[2],type:'Fresh Booking',propertyType:p[3],status:'Source verification required',price:'Latest price on request',land:'Verify latest RERA / builder sheet',brief:`${p[1]} is listed in the Moneyland Corporation Gurgaon project directory. Exact land parcel, towers, unit mix, approvals, possession and current inventory should be confirmed from the latest official builder/RERA material before a buyer proceeds.`,image:null}));

function $(s){return document.querySelector(s)} function $$(s){return [...document.querySelectorAll(s)]}
function wa(){window.open(ML.whatsapp,'_blank')}
function setText(){ $$('.js-company').forEach(e=>e.textContent=ML.company); $$('.js-tagline').forEach(e=>e.textContent=ML.tagline); $$('.js-phone').forEach(e=>e.textContent='+91 '+ML.phone); $$('.js-email').forEach(e=>e.textContent=ML.email); $$('.js-address').forEach(e=>e.textContent=ML.address); $$('.js-rera').forEach(e=>e.textContent=ML.rera); $$('.js-gst').forEach(e=>e.textContent=ML.gst); }
function populateSelect(id,arr){const e=$(id);if(!e)return;e.innerHTML='<option value="">All Gurgaon</option>'+[...new Set(arr)].map(x=>`<option>${x}</option>`).join('')}
function imageFallback(p){const label=p.propertyType==='Builder Floor'?'BUILDER FLOOR':p.propertyType==='Flat / Apartment'?'FLAT / APARTMENT':p.propertyType.toUpperCase();return `<div class="verified-image-placeholder"><span>${label}</span><small>Official project image will be published after source verification</small></div>`}
function projectCard(p){return `<article class="property-card project-card"><div class="project-img">${p.image?`<img src="${p.image}" alt="${p.name}" loading="lazy">`:imageFallback(p)}<span class="project-badge">FRESH BOOKING</span></div><div class="pc-body"><div><span class="badge">${p.builder}</span><span class="badge verified">✓ Directory</span></div><h3>${p.name}</h3><p>${p.loc} • ${p.propertyType}</p><strong>${p.price}</strong><a class="btn btn-purple full" href="property.html?project=${p.id}">View Project</a></div></article>`}
function ownerCards(){return JSON.parse(localStorage.getItem('ml_owner_listings')||'[]').filter(x=>x.approved).map(x=>`<article class="property-card"><div class="prop-img owner-placeholder">VERIFIED OWNER PROPERTY</div><div class="pc-body"><span class="badge verified">✓ Verified</span><h3>${x.type} • ${x.location}</h3><p>${x.bhk||''} • ${x.size||''}</p><strong>${x.demand||'Price on request'}</strong><a class="btn btn-dark full" href="property.html?id=${x.id}">View Property</a></div></article>`).join('')}
function renderCards(){const wrap=$('#propertyGrid');if(!wrap)return;const loc=$('#filterLocation')?.value||'', search=($('#projectSearch')?.value||'').trim().toLowerCase();const list=projects.filter(p=>(!loc||p.loc.includes(loc)||p.name.toLowerCase().includes(loc.toLowerCase()))&&(!search||`${p.name} ${p.builder} ${p.loc}`.toLowerCase().includes(search)));const displayList=location.pathname.endsWith('index.html')||location.pathname==='/'?list.slice(0,12):list;wrap.innerHTML=displayList.map(projectCard).join()+ownerCards()||'<div class="empty">No matching project found.</div>';const count=$('#projectCount');if(count)count.textContent=`${list.length} projects in directory`}
function showBidGate(){const rent=location.search.includes('rent');const min=rent?5000:50000;alert(`Bid access is locked until verification.\n\nMinimum token: ₹${min.toLocaleString('en-IN')} for ${rent?'rent':'sale'} deal.\n\nPlease login/register, complete token payment and wait for Moneyland Corporation admin approval.`)}
function bidAllowed(){return localStorage.getItem('ml_bid_verified')==='1'}
function detailProject(){const id=new URLSearchParams(location.search).get('project');const p=projects.find(x=>x.id===id);if(!p)return;const map={'.js-project-name':p.name,'.js-project-builder':p.builder,'.js-project-location':p.loc,'.js-project-type':p.propertyType,'.js-project-price':p.price,'.js-project-land':p.land,'.js-project-status':p.status,'.js-project-brief':p.brief};Object.entries(map).forEach(([sel,val])=>{const e=$(sel);if(e)e.textContent=val});const g=$('#projectDetailImage');if(g){if(p.image){g.innerHTML=`<img src="${p.image}" alt="${p.name}">`}else g.innerHTML=imageFallback(p)};document.title=`${p.name} | ${ML.company}`}
function init(){setText();populateSelect('#filterLocation',localities);populateSelect('#propertyLocation',localities);renderCards();detailProject();$$('#filterLocation').forEach(e=>e.addEventListener('change',renderCards));$('#projectSearch')?.addEventListener('input',renderCards);$$('.js-wa').forEach(e=>e.addEventListener('click',wa));const menu=$('.menu');if(menu)menu.onclick=()=>document.body.classList.toggle('nav-open');
 const bid=$('#bidForm');if(bid){if(!bidAllowed()){$('#bidGate')?.classList.remove('hidden');const submit=bid.querySelector('button[type="submit"]');if(submit){submit.type='button';submit.onclick=showBidGate}}else{$('#bidGate')?.classList.add('hidden');bid.onsubmit=e=>{e.preventDefault();alert('Bid submitted successfully. Your bid is now under review.');bid.reset()}}}
 const login=$('#userLogin');if(login)login.onsubmit=e=>{e.preventDefault();localStorage.setItem('ml_demo_session','1');location.href='dashboard.html'};
 const reg=$('#registerForm');if(reg)reg.onsubmit=e=>{e.preventDefault();localStorage.setItem('ml_demo_session','1');alert('Registration successful. You can now list a property.');location.href='list-property.html'};
 $$('.logout').forEach(b=>b.onclick=()=>{localStorage.removeItem('ml_demo_session');localStorage.removeItem('ml_bid_verified');location.href='index.html'});
 const list=$('#listForm');if(list)list.onsubmit=e=>{e.preventDefault();const photos=$('#photos'),docs=$('#docs'),aadhar=$('#aadharNumber');if(aadhar&&aadhar.value.replace(/\D/g,'').length!==12)return alert('Please enter a valid 12-digit Aadhaar number for verification.');if(photos&&photos.files.length>10)return alert('Maximum 10 property photos allowed.');if(docs&&!docs.files.length)return alert('Please attach the original property document.');const listing={id:'owner-'+Date.now(),type:$('#propertyType')?.value||'Property',location:$('#propertyLocation')?.value||'',bhk:$('#bhk')?.value||'',size:$('#size')?.value||'',demand:$('#demand')?.value||'',approved:false};const arr=JSON.parse(localStorage.getItem('ml_owner_listings')||'[]');arr.push(listing);localStorage.setItem('ml_owner_listings',JSON.stringify(arr));alert('Property submitted for verification. It will appear publicly only after Moneyland Corporation admin approval.');location.href='dashboard.html'};
 const adminApprove=$('#adminApproveBid');if(adminApprove)adminApprove.onclick=()=>{localStorage.setItem('ml_bid_verified','1');alert('Buyer verification approved. Bid access is now unlocked in this browser.');location.reload()};
 const adminListing=$('#adminApproveListing');if(adminListing)adminListing.onclick=()=>{const arr=JSON.parse(localStorage.getItem('ml_owner_listings')||'[]');arr.forEach(x=>x.approved=true);localStorage.setItem('ml_owner_listings',JSON.stringify(arr));alert('Pending owner listings approved for demo.');location.reload()};
}
document.addEventListener('DOMContentLoaded',init);
