const ML={
 phone:'8178593108', whatsapp:'https://wa.me/918178593108', email:'mailto:rrahmawat@gmail.com', rera:'RC/HARERA/GGM/4078/3673/2026/113', address:'R1/205, M3M 65th Avenue, Sector 65, Gurgaon, Gurugram, Haryana - 122018', website:'www.moneylandcorporation.com', tagline:'Gurgaon Ki Har Property, Sirf Ek Baar, Malik Se Direct'
};
const sectors=Array.from({length:115},(_,i)=>`Sector ${i+1}`); const localities=['DLF Phase 1','DLF Phase 2','DLF Phase 3','DLF Phase 4','Golf Course Road','Golf Course Extension Road','MG Road','Sohna Road','Dwarka Expressway','New Gurgaon','Southern Peripheral Road','SPR','Nirvana Country','Sushant Lok 1','Sushant Lok 2','Sushant Lok 3','Palam Vihar','South City 1','South City 2','Malibu Town','M3M','Gwal Pahari','Faridabad Road','Manesar','Sector 57','Sector 58','Sector 59','Sector 60','Sector 61','Sector 62','Sector 63','Sector 64','Sector 65','Sector 66','Sector 67','Sector 68','Sector 69','Sector 70','Sector 70A','Sector 71','Sector 72','Sector 73','Sector 74','Sector 75','Sector 76','Sector 77','Sector 78','Sector 79','Sector 80','Sector 81','Sector 82','Sector 83','Sector 84','Sector 85','Sector 86','Sector 87','Sector 88','Sector 89','Sector 90','Sector 91','Sector 92','Sector 93','Sector 94','Sector 95','Sector 96','Sector 97','Sector 98','Sector 99','Sector 100','Sector 101','Sector 102','Sector 103','Sector 104','Sector 105','Sector 106','Sector 107','Sector 108','Sector 109','Sector 110','Sector 111','Sector 112','Sector 113','Sector 114','Sector 115'];
const propertyTypes=['Flat / Apartment','Builder Floor','Independent Floor','Villa','Plot','Commercial Shop','Office Space','Warehouse','Showroom','Industrial Property','Independent House','Farm House'];
function $(s){return document.querySelector(s)} function $$(s){return [...document.querySelectorAll(s)]}
function wa(){location.href=ML.whatsapp} function setText(){ $$('.js-phone').forEach(e=>e.textContent='+91 '+ML.phone); $$('.js-email').forEach(e=>e.textContent='rrahmawat@gmail.com'); $$('.js-address').forEach(e=>e.textContent=ML.address); $$('.js-rera').forEach(e=>e.textContent=ML.rera); }
function populateSelect(id,arr){const e=$(id);if(!e)return;e.innerHTML='<option value="">All</option>'+arr.map(x=>`<option>${x}</option>`).join('')}
function propertyData(){return [
['p1','Flat / Apartment','DLF Phase 3','3 BHK','₹4.20 Cr','2,400 sq.ft.'],['p2','Villa','Golf Course Road','4 BHK','₹8.50 Cr','4,800 sq.ft.'],['p3','Plot','Sector 65','—','₹2.45 Cr','240 sq.yd.'],['p4','Office Space','DLF Phase 1','—','₹6.75 Cr','5,000 sq.ft.'],['p5','Commercial Shop','Sector 57','—','₹2.50 Cr','1,200 sq.ft.'],['p6','Builder Floor','Sector 50','3 BHK','₹2.10 Cr','1,850 sq.ft.'],['p7','Independent Floor','Sushant Lok 1','4 BHK','₹3.75 Cr','3,100 sq.ft.'],['p8','Warehouse','Manesar','—','₹1.80 Lakh/mo','8,000 sq.ft.'],['p9','Showroom','MG Road','—','₹3.20 Lakh/mo','3,000 sq.ft.']];}
function renderCards(){const wrap=$('#propertyGrid');if(!wrap)return;let data=propertyData();const type=$('#filterType')?.value||'',loc=$('#filterLocation')?.value||'';data=data.filter(x=>(!type||x[1]===type)&&(!loc||x[2]===loc));wrap.innerHTML=data.map(x=>`<article class="property-card"><div class="prop-img">${x[1]}</div><div class="pc-body"><div><span class="badge verified">✓ Moneyland Verified</span><span class="badge">Owner Verified</span></div><h3>${x[1]} • ${x[2]}</h3><p>${x[3]} ${x[5]?'• '+x[5]:''}</p><strong>${x[4]}</strong><a class="btn btn-dark full" href="property.html?id=${x[0]}">View Property</a></div></article>`).join('')||'<div class="empty">No verified property found for this filter.</div>';}
function init(){setText();populateSelect('#filterType',propertyTypes);populateSelect('#filterLocation',localities);renderCards(); $$('#filterType,#filterLocation').forEach(e=>e.addEventListener('change',renderCards)); $$('.js-wa').forEach(e=>e.addEventListener('click',wa)); const menu=$('.menu');if(menu)menu.onclick=()=>document.body.classList.toggle('nav-open'); const form=$('#bidForm');if(form)form.onsubmit=e=>{e.preventDefault();alert('Bid submitted. The owner can see this bid and approve/reject it. Contact details are not shared.');form.reset()}; const login=$('#aadhaarLogin');if(login)login.onsubmit=e=>{e.preventDefault();localStorage.setItem('ml_demo_session','1');location.href='dashboard.html'}; const logout=$('.logout');if(logout)logout.onclick=()=>{localStorage.removeItem('ml_demo_session');location.href='index.html'}; const list=$('#listForm');if(list)list.onsubmit=e=>{e.preventDefault();const photos=$('#photos');const docs=$('#docs');if(photos.files.length>10)return alert('Maximum 10 property photos allowed.');if(!docs.files.length)return alert('Please attach the property document.');alert('Testing submission saved locally. Connect Supabase to create the live listing and verification request.');};}
document.addEventListener('DOMContentLoaded',init);
